#!/usr/bin/env node
/**
 * extrachill-network Homeboy rig.
 *
 * Boots the full 11-site Extra Chill subdomain multisite network inside a
 * disposable WP Codebox WordPress Playground sandbox: real per-domain sites
 * (wp_insert_site(), SUBDOMAIN_INSTALL), every network plugin and per-site
 * plugin mounted from its owning repository's release artifact by default,
 * the shared theme, and a per-site activation matrix that matches production.
 *
 * See README.md for the full design rationale, the settings this rig reads,
 * and the documented gaps (theme remote sourcing, a handful of excluded
 * components with no public source).
 */
import { mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const packageRoot = path.dirname(fileURLToPath(import.meta.url));

const WP_CODEBOX_MAX_BUFFER_BYTES = 80 * 1024 * 1024;
export const DEMO_MIN_WP_CODEBOX_VERSION = '0.31.0';

// Extra Chill's real product zips (WooCommerce, Gutenberg, data-machine, ...)
// comfortably exceed WP Codebox's 25 MB/100 MB/5000-file defaults, which are
// sized for a single consumer plugin under test, not a ~30-component network.
const DEFAULT_DOWNLOAD_ENV = {
  WP_CODEBOX_ALLOW_NETWORK_DOWNLOADS: '1',
  WP_CODEBOX_ALLOWED_DOWNLOAD_HOSTS: 'downloads.wordpress.org,github.com,objects.githubusercontent.com,release-assets.githubusercontent.com',
  WP_CODEBOX_MAX_DOWNLOAD_BYTES: String(100 * 1024 * 1024),
  WP_CODEBOX_MAX_EXTRACTED_BYTES: String(400 * 1024 * 1024),
  WP_CODEBOX_MAX_EXTRACTED_FILES: String(20000),
};

async function loadJson(relativePath) {
  return JSON.parse(await readFile(path.join(packageRoot, relativePath), 'utf8'));
}

// The EC_BLOG_ID_* constants (extrachill-network inc/core/blog-ids.php) carry
// production's blog IDs behind wp-config-style if(!defined()) guards. A fresh
// disposable install assigns new sequential blog IDs, so on an unaligned boot
// ec_is_events_site() and every cross-site route built on ec_get_blog_id()
// silently target the WRONG site (the docs site lands on blog 7 and inherits
// the events site's identity). This rig therefore projects its domain
// topology into those constants at runtime via a generated mu-plugin: each
// well-known domain is resolved against the actual sites table on every
// request, so the plugin set's expectations hold on any fresh install. This
// is rig infrastructure (domain resolution), not a product workaround; the
// upstream fix is for ec_get_blog_id() to resolve by domain itself.
const EC_DOMAIN_TO_BLOG_ID_CONSTANT = {
  'extrachill.com': 'EC_BLOG_ID_MAIN',
  'community.extrachill.com': 'EC_BLOG_ID_COMMUNITY',
  'shop.extrachill.com': 'EC_BLOG_ID_SHOP',
  'artist.extrachill.com': 'EC_BLOG_ID_ARTIST',
  'events.extrachill.com': 'EC_BLOG_ID_EVENTS',
  'newsletter.extrachill.com': 'EC_BLOG_ID_NEWSLETTER',
  'docs.extrachill.com': 'EC_BLOG_ID_DOCS',
  'wire.extrachill.com': 'EC_BLOG_ID_WIRE',
  'studio.extrachill.com': 'EC_BLOG_ID_STUDIO',
  'extrachill.link': 'EC_BLOG_ID_LINK_PAGES',
  'auth.extrachill.com': 'EC_BLOG_ID_AUTH',
};

export const DOMAIN_IDS_MU_PLUGIN_FILENAME = 'ec-network-domain-ids.php';

export function domainIdsMuPluginSource(topology) {
  const unknownDomains = Object.keys(EC_DOMAIN_TO_BLOG_ID_CONSTANT).filter(
    (domain) => !topology.sites.some((site) => site.domain === domain),
  );
  if (unknownDomains.length > 0) {
    throw new Error(`network-topology.json is missing rig domains with blog-ID constants: ${unknownDomains.join(', ')}`);
  }
  const entries = Object.entries(EC_DOMAIN_TO_BLOG_ID_CONSTANT)
    .map(([domain, constant]) => `\t\t'${domain}' => '${constant}',`)
    .join('\n');
  return `<?php
/**
 * GENERATED by rigs/extrachill-network/run.mjs from network-topology.json.
 * Do not edit: regenerate via the rig (homeboy rig install / up).
 *
 * Resolves the EC_BLOG_ID_* constants (extrachill-network inc/core/blog-ids.php)
 * from the actual sites table BY DOMAIN on every request. A fresh disposable
 * install assigns new sequential blog IDs, so the hardcoded production
 * defaults (events = 7, newsletter = 9, ...) would silently misroute every
 * ec_get_blog_id()/ec_is_events_site() consumer to the wrong site. The
 * if(!defined()) guards in blog-ids.php exist precisely so an earlier
 * definition wins; mu-plugins load before regular plugins.
 *
 * Skipped while WP_INSTALLING and on any request where the multisite API is
 * not loaded yet (the install-time blueprint request runs mu-plugins before
 * ms-blogs.php) -- the production defaults then apply harmlessly and later
 * requests resolve by domain.
 *
 * @package ExtraChillNetwork
 */

if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) || ! function_exists( 'get_sites' ) ) {
\treturn;
}

function ec_rig_network_resolve_domain_blog_ids() {
\tstatic $map = array(
${entries}
\t);
\tforeach ( $map as $domain => $constant ) {
\t\tif ( defined( $constant ) ) {
\t\t\tcontinue;
\t\t}
\t\t$sites = get_sites( array( 'domain' => $domain, 'number' => 1, 'fields' => 'all' ) );
\t\tif ( empty( $sites ) ) {
\t\t\tcontinue;
\t\t}
\t\tdefine( $constant, (int) $sites[0]->blog_id );
\t}
}
ec_rig_network_resolve_domain_blog_ids();
`;
}

export async function writeDomainIdsMuPlugin(directory, topology) {
  await mkdir(directory, { recursive: true });
  const target = path.join(directory, DOMAIN_IDS_MU_PLUGIN_FILENAME);
  await writeFile(target, domainIdsMuPluginSource(topology));
  return target;
}

export const SANDBOX_COMPAT_MU_PLUGIN_FILENAME = 'ec-network-sandbox-compat.php';

/**
 * Sandbox compatibility mu-plugin (extrachill-network#302, #299): the
 * disposable-runtime gaps every browser journey hits. Each substitutes a
 * missing piece of infrastructure, never product behaviour, and exists only
 * inside the disposable boot.
 */
export function sandboxCompatMuPluginSource() {
  return `<?php
/**
 * GENERATED by rigs/extrachill-network/run.mjs (extrachill-network#302).
 * Disposable-sandbox compatibility only; never deployed.
 */

/*
 * 1. http vs https. The sandbox serves plain http, but ec_get_site_url() and
 *    the Link Pages public base URL build https:// URLs, so cross-site hops
 *    (/join, bridge cards, editor handoff, canonical redirects) dead-end on a
 *    TLS port nothing answers. Answer with each site's real home URL through
 *    the override extrachill-network ships for dev environments, and
 *    downgrade redirects to network hosts.
 */
add_filter(
\t'ec_site_url_override',
\tstatic function ( $url, $key, $blog_id ) {
\t\tunset( $key );
\t\treturn $blog_id ? untrailingslashit( get_home_url( (int) $blog_id ) ) : $url;
\t},
\t10,
\t3
);
add_filter(
\t'wp_redirect',
\tstatic function ( $location ) {
\t\treturn is_string( $location ) ? preg_replace( '#^https://((?:[a-z0-9-]+\\\\.)?extrachill\\\\.(?:com|link))(?=[/?\\\\#]|$)#i', 'http://$1', $location ) : $location;
\t},
\tPHP_INT_MAX - 1
);

/*
 * 1b. Same downgrade for URLs the product emits directly rather than via a
 *     redirect: escaped links in HTML (clean_url) and URLs inside REST
 *     responses (e.g. the Link Page owner pencil's manage_url). Production
 *     is https end to end.
 */
function ec_rig_downgrade_network_urls( $value ) {
	if ( is_string( $value ) ) {
		return preg_replace( '#https://((?:[a-z0-9-]+\\.)?extrachill\\.(?:com|link))(?=[/?\\#"]|$)#i', 'http://$1', $value );
	}
	if ( is_array( $value ) ) {
		return array_map( 'ec_rig_downgrade_network_urls', $value );
	}
	return $value;
}
add_filter( 'clean_url', 'ec_rig_downgrade_network_urls', PHP_INT_MAX );
add_filter(
	'rest_post_dispatch',
	static function ( $response ) {
		if ( $response instanceof WP_REST_Response ) {
			$response->set_data( ec_rig_downgrade_network_urls( $response->get_data() ) );
		}
		return $response;
	},
	PHP_INT_MAX
);

/*
 * 3. No persistent object cache. Redis is an excluded component on this rig,
 *    and the network's two atomic abuse limiters fail closed without one:
 *    Extra Chill Users registration (registration_limiter_unavailable, 503;
 *    every browser sign-up) and extrachill-api public writes (register,
 *    login, refresh). Both expose a store seam; answer them with a
 *    site-option counter. Requests are serialized, so this is not a claim
 *    of atomicity under real concurrency (extrachill-network#299).
 */
function ec_rig_sandbox_counter( $key, $ttl ) {
	$state = get_site_option( 'ec_rig_sandbox_counters', array() );
	$now   = time();
	$entry = $state[ $key ] ?? array( 'count' => 0, 'expires' => $now + max( 1, (int) $ttl ) );
	if ( $entry['expires'] <= $now ) {
		$entry = array( 'count' => 0, 'expires' => $now + max( 1, (int) $ttl ) );
	}
	++$entry['count'];
	$state[ $key ] = $entry;
	update_site_option( 'ec_rig_sandbox_counters', $state );
	return (int) $entry['count'];
}
add_filter(
	'extrachill_api_rate_limit_store',
	static function () {
		return 'ec_rig_sandbox_counter';
	}
);
add_filter(
	'extrachill_users_registration_admitter',
	static function ( $admitter ) {
		if ( ! function_exists( 'extrachill_users_registration_attempt_key' ) || ! defined( 'EXTRACHILL_USERS_REGISTRATION_RATE_WINDOW' ) || ! defined( 'EXTRACHILL_USERS_REGISTRATION_RATE_LIMIT' ) ) {
			return $admitter;
		}
		return static function () {
			$key = extrachill_users_registration_attempt_key();
			if ( '' === $key ) {
				return new WP_Error( 'registration_limiter_unavailable', 'Registration is temporarily unavailable.', array( 'status' => 503 ) );
			}
			$window     = EXTRACHILL_USERS_REGISTRATION_RATE_WINDOW;
			$expires_at = ( intdiv( time(), $window ) + 1 ) * $window;
			$count      = ec_rig_sandbox_counter( 'registration_' . $key, 2 * $window );
			return $count > EXTRACHILL_USERS_REGISTRATION_RATE_LIMIT && function_exists( 'extrachill_users_registration_rate_limit_error' )
				? extrachill_users_registration_rate_limit_error( $expires_at )
				: true;
		};
	}
);

/*
 * 4. SQLite has no MySQL advisory locks, so every GET_LOCK()-serialized write
 *    (Link Page creation and saves, artist membership) fails closed. Requests
 *    are serialized through one PHP runtime here, so answer as MySQL would.
 *    Not a claim of concurrency safety.
 */
add_filter(
\t'query',
\tstatic function ( $query ) {
\t\tif ( is_string( $query ) && preg_match( '/^\\\\s*SELECT\\\\s+(GET_LOCK|RELEASE_LOCK|IS_FREE_LOCK)\\\\s*\\\\(/i', $query ) ) {
\t\t\treturn 'SELECT 1';
\t\t}
\t\treturn $query;
\t}
);
`;
}

export async function writeSandboxCompatMuPlugin(directory) {
  await mkdir(directory, { recursive: true });
  const target = path.join(directory, SANDBOX_COMPAT_MU_PLUGIN_FILENAME);
  await writeFile(target, sandboxCompatMuPluginSource());
  return target;
}

export function journeySelection(settings) {
  if (settings.extrachill_journeys === undefined) {
    return [];
  }
  const value = settings.extrachill_journeys;
  if (!Array.isArray(value) || value.some((id) => typeof id !== 'string' || id.trim() === '')) {
    throw new Error('extrachill_journeys must be an array of non-empty journey ID strings, e.g. ["gardner-event-rsvp"].');
  }
  const seen = new Set();
  for (const id of value) {
    if (seen.has(id)) {
      throw new Error(`extrachill_journeys lists journey '${id}' more than once.`);
    }
    seen.add(id);
  }
  return value.map((id) => id.trim());
}

/**
 * `extrachill_journey_seed`: an optional, generic deterministic string a
 * journey's own seed.php may read back (via
 * `get_site_option('ec_rig_journey_seed', ...)`) to build a replayable,
 * seeded case plan. The rig treats it as an opaque string; it never inspects
 * or names what any journey does with it.
 */
export function journeySeedSetting(settings) {
  if (settings.extrachill_journey_seed === undefined) {
    return undefined;
  }
  const value = settings.extrachill_journey_seed;
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error('extrachill_journey_seed must be a non-empty string.');
  }
  return value;
}

function journeySeedStep(seed) {
  const encoded = Buffer.from(JSON.stringify(seed)).toString('base64');
  return {
    command: 'wordpress.run-php',
    args: [`code=update_site_option( 'ec_rig_journey_seed', json_decode( base64_decode( '${encoded}' ) ) );`],
    metadata: { kind: 'journey-seed-setting' },
  };
}

export async function availableJourneys() {
  const root = path.join(packageRoot, 'journeys');
  try {
    const entries = await readdir(root, { withFileTypes: true });
    return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort();
  } catch {
    return [];
  }
}

async function loadJourney(id, topology) {
  const dir = path.join(packageRoot, 'journeys', id);
  const journeyPath = path.join(dir, 'journey.json');
  let journey;
  try {
    journey = JSON.parse(await readFile(journeyPath, 'utf8'));
  } catch (error) {
    throw new Error(`Journey '${id}' has an unreadable journey.json: ${error.message}`);
  }
  const personaExists = async (file) => {
    try {
      await readFile(path.join(packageRoot, 'personas', file), 'utf8');
      return true;
    } catch {
      return false;
    }
  };
  const codeFileExists = async (file) => {
    try {
      await readFile(path.join(dir, file), 'utf8');
      return true;
    } catch {
      return false;
    }
  };
  await validateJourneyDocument(journey, id, topology, personaExists, codeFileExists);
  return { journey, dir };
}

/**
 * Validate a journey document against the journey contract
 * (extrachill-network/journey/v1). `personaExists` and `codeFileExists` are
 * async predicates so the rules are testable without fixture files.
 */
export async function validateJourneyDocument(journey, id, topology, personaExists = async () => true, codeFileExists = async () => true) {
  if (journey.schema !== 'extrachill-network/journey/v1') {
    throw new Error(`Journey '${id}' must declare schema "extrachill-network/journey/v1", got ${JSON.stringify(journey.schema)}.`);
  }
  if (journey.id !== id) {
    throw new Error(`Journey '${id}' journey.json declares id ${JSON.stringify(journey.id)}; the id must match the directory name.`);
  }
  if (!Array.isArray(journey.sites) || journey.sites.length === 0) {
    throw new Error(`Journey '${id}' must declare a non-empty "sites" array of topology domains.`);
  }
  for (const domain of journey.sites) {
    if (!topology.sites.some((site) => site.domain === domain)) {
      throw new Error(`Journey '${id}' references site '${domain}', which is not a domain in network-topology.json. Sites are resolved by domain, never by blog ID.`);
    }
  }
  if (journey.persona?.file && !(await personaExists(journey.persona.file))) {
    throw new Error(`Journey '${id}' pins persona file '${journey.persona.file}', which is missing from rigs/extrachill-network/personas/.`);
  }
  for (const phase of ['seed', 'grade']) {
    if (journey[phase]?.codeFile && !(await codeFileExists(journey[phase].codeFile))) {
      throw new Error(`Journey '${id}' ${phase}.codeFile '${journey[phase].codeFile}' does not exist in journeys/${id}/.`);
    }
  }
  if (journey.demo !== undefined) {
    const demo = journey.demo;
    if (!isRecord(demo) || !isRecord(demo.video) || !/^\d+x\d+$/.test(demo.video.viewport ?? '')) {
      throw new Error(`Journey '${id}' demo.video.viewport must be WxH.`);
    }
    if (demo.video.size !== undefined && !/^\d+x\d+$/.test(demo.video.size)) throw new Error(`Journey '${id}' demo.video.size must be WxH.`);
    if (demo.video.output !== undefined && (!isRecord(demo.video.output) || !['width', 'height', 'fps'].every((key) => Number.isInteger(demo.video.output[key]) && demo.video.output[key] > 0))) throw new Error(`Journey '${id}' demo.video.output requires positive integer width, height, and fps.`);
    if (typeof demo.theme !== 'string' || !/^[a-z0-9-]+\.json$/.test(demo.theme)) throw new Error(`Journey '${id}' demo.theme must name a JSON theme file.`);
    try { await readFile(path.join(packageRoot, 'demo-themes', demo.theme), 'utf8'); } catch { throw new Error(`Journey '${id}' references unknown demo theme '${demo.theme}'.`); }
    if (demo.steps !== undefined) {
      const markers = new Set(journey.steps.map((step) => step.marker).filter(Boolean));
      if (!Array.isArray(demo.steps) || demo.steps.some((step) => !markers.has(step.after ?? step.marker))) throw new Error(`Journey '${id}' demo.steps references unknown markers.`);
    }
    if (!isRecord(demo.presentation)) throw new Error(`Journey '${id}' demo.presentation must be an object.`);
    if (demo.environment !== undefined && (!isRecord(demo.environment) || (demo.environment.colorScheme !== undefined && !['light', 'dark', 'no-preference'].includes(demo.environment.colorScheme)))) throw new Error(`Journey '${id}' demo.environment must be an object with colorScheme light, dark, or no-preference.`);
    if (demo.pacing !== undefined && (!isRecord(demo.pacing) || ['settleMs', 'minCaptionMs'].some((key) => demo.pacing[key] !== undefined && (!Number.isInteger(demo.pacing[key]) || demo.pacing[key] < 0)))) throw new Error(`Journey '${id}' demo.pacing requires non-negative integer settleMs and minCaptionMs values.`);
    if (demo.cover !== undefined && (!isRecord(demo.cover) || typeof demo.cover.marker !== 'string' || !journeyMarkers(journey).includes(demo.cover.marker))) throw new Error(`Journey '${id}' demo.cover.marker must reference an existing step marker.`);
  }
  if (journey.fixtureMuPlugins !== undefined) {
    if (!Array.isArray(journey.fixtureMuPlugins) || journey.fixtureMuPlugins.length === 0 || journey.fixtureMuPlugins.some((file) => typeof file !== 'string' || file.trim() === '')) {
      throw new Error(`Journey '${id}' fixtureMuPlugins must be a non-empty array of non-empty file names relative to journeys/${id}/.`);
    }
    for (const file of journey.fixtureMuPlugins) {
      if (!(await codeFileExists(file))) {
        throw new Error(`Journey '${id}' fixtureMuPlugins entry '${file}' does not exist in journeys/${id}/.`);
      }
    }
  }
  assertJourneyStepScoping(id, journey);
}

export function assembleDemoArgs(demo, theme = {}) {
  const viewport = demo.video.viewport;
  return [
    'capture=steps,console,errors,network,screenshot,video',
    `viewport=${viewport}`,
    ...(demo.video.size ? [`video-size=${demo.video.size}`] : []),
    `presentation-json=${JSON.stringify(demo.presentation)}`,
    `annotation-theme-json=${JSON.stringify(theme)}`,
    ...(demo.environment ? [`browser-environment-json=${JSON.stringify(demo.environment)}`] : []),
    ...(Number.parseInt(viewport.split('x')[0], 10) <= 600 ? ['is-mobile=true', 'has-touch=true'] : []),
  ];
}

export function paceDemoSteps(raw, pacing = {}) {
  if (!pacing.settleMs && !pacing.minCaptionMs) return raw;
  const steps = typeof raw === 'string' ? JSON.parse(raw) : raw;
  const paced = [];
  for (const step of steps) {
    paced.push(step);
    if ((step.kind === 'navigate' || step.kind === 'click') && pacing.settleMs > 0) {
      paced.push({ kind: 'waitFor', waitFor: 'duration', duration: `${pacing.settleMs}ms` });
    }
    // A caption with its own durationMs is followed by an authored wait; only
    // untimed captions need the minimum on-screen time inserted.
    if (step.kind === 'annotate' && step.shape === 'caption' && pacing.minCaptionMs > 0 && step.durationMs === undefined) {
      paced.push({ kind: 'waitFor', waitFor: 'duration', duration: `${pacing.minCaptionMs}ms` });
    }
  }
  return JSON.stringify(paced);
}

export function demoEncodeArgs(input, output, demo) {
  const out = demo.video.output;
  const filters = [
    ...(out ? [`scale=${out.width}:${out.height}:flags=lanczos`] : []),
    ...(out?.fps ? [`fps=${out.fps}`] : []),
    'format=yuv420p',
  ];
  return ['-y', '-v', 'error', '-i', input, '-vf', filters.join(','), '-c:v', 'libx264', '-preset', 'slow', '-crf', '18', '-movflags', '+faststart', '-an', output];
}

export function journeyMarkers(journey) {
  const markers = [];
  for (const step of journey.steps) {
    const raw = (step.args ?? []).find((arg) => arg.startsWith('steps-json='));
    if (!raw) continue;
    try {
      for (const action of JSON.parse(raw.slice('steps-json='.length))) if (action.marker) markers.push(action.marker);
    } catch { /* validated elsewhere */ }
  }
  return markers;
}

function assertJourneyStepScoping(id, journey) {
  journey.steps.forEach((step, index) => {
    const args = step.args ?? [];
    const urls = args.filter((arg) => arg.startsWith('url=')).map((arg) => arg.slice('url='.length));
    const allowed = new Set(journey.sites);
    for (const rawUrl of urls) {
      let host;
      try {
        host = new URL(rawUrl).host;
      } catch {
        throw new Error(`Journey '${id}' step ${index} has a non-absolute url '${rawUrl}'. Journey steps use absolute http://<domain>/ URLs so every step targets a declared site by domain.`);
      }
      if (!allowed.has(host)) {
        throw new Error(`Journey '${id}' step ${index} targets '${host}', which is outside the journey's declared sites (${[...allowed].join(', ')}).`);
      }
    }
    for (const argKey of ['route-host', 'allow-host']) {
      // Both args are wp-codebox "repeatable" hostnames (route-host also
      // accepts one comma-separated value): a journey step driving a real
      // cross-site flow (e.g. a browser-handoff redirect) legitimately
      // declares more than one. Every declared host -- not just the first
      // occurrence -- must stay inside the journey's declared sites.
      const hosts = args
        .filter((arg) => arg.startsWith(`${argKey}=`))
        .flatMap((arg) => arg.slice(argKey.length + 1).split(','))
        .map((host) => host.trim())
        .filter((host) => host !== '');
      for (const host of hosts) {
        if (!allowed.has(host)) {
          throw new Error(`Journey '${id}' step ${index} sets ${argKey} to '${host}', outside the journey's declared sites.`);
        }
      }
    }
    if (step.metadata?.kind !== undefined && step.metadata.kind !== 'journey-browser-step') {
      throw new Error(`Journey '${id}' step ${index} uses reserved metadata kind '${step.metadata.kind}'.`);
    }
  });
}

function journeyStep(journey, dir, step) {
  const substitute = (value) => (typeof value === 'string' ? value.replaceAll('${journey.dir}', dir).replaceAll('${journey.id}', journey.id) : value);
  // Emit only keys the WP Codebox recipe schema accepts: it rejects unknown
  // step properties, so journey-only annotations (e.g. a step `marker`) must
  // never leak into the recipe.
  const { command, args, metadata, timeoutMs, env } = step;
  return {
    command,
    ...(timeoutMs !== undefined ? { timeoutMs } : {}),
    ...(env !== undefined ? { env } : {}),
    // See journeyPhaseStep: every journey step is isolated from the others.
    allowFailure: true,
    args: (args ?? []).map(substitute),
    metadata: { ...(metadata ?? {}), kind: metadata?.kind ?? 'journey-browser-step', journey: journey.id },
  };
}

function journeyPhaseStep(journey, dir, phase) {
  const phaseConfig = journey[phase];
  if (!phaseConfig?.codeFile) {
    return undefined;
  }
  return {
    command: 'wordpress.run-php',
    args: [`code-file=${path.join(dir, phaseConfig.codeFile)}`],
    ...(phaseConfig.timeoutMs ? { timeoutMs: phaseConfig.timeoutMs } : {}),
    // Journey isolation: one journey's fatal must not stop the recipe and
    // discard every other selected journey's results. The failure is still
    // recorded (stepFailures) and the journeys workflow fails on it.
    allowFailure: true,
    metadata: { kind: `journey-${phase}`, journey: journey.id },
  };
}

/**
 * wp-codebox's wordpress.run-php always bootstraps every request with the
 * SAME simulated identity -- HTTP_HOST/REQUEST_URI copied from wp-config.php's
 * DOMAIN_CURRENT_SITE/PATH_CURRENT_SITE (see
 * @automattic/wp-codebox-playground's multisiteRequestBootstrapPhp()), i.e.
 * every single run-php call looks identical to an anonymous GET of the
 * primary site's homepage. extrachill-cache's advanced-cache.php drop-in
 * (correctly, for a real front-end request) serves a stored page for that
 * exact identity and exits before WordPress finishes loading -- BEFORE our
 * injected eval code ever runs -- the moment any earlier step (a baseline
 * browser-probe, a journey browser-action) has actually visited that
 * homepage as a real anonymous visitor and warmed the cache. That produces a
 * run-php step wp-codebox itself reports as "succeeded" while our PHP never
 * executed at all: this rig hit it for real (the journey's seed AND grade
 * run-php steps both silently returned cached homepage HTML, evidenced by an
 * identical "Cached by Extra Chill Cache" timestamp on both). Filed upstream
 * at Automattic/wp-codebox with a minimal repro; wp-cli's own bootstrap
 * (wp-cli-command-handlers.js) never sets $_SERVER['REQUEST_METHOD'], so
 * advanced-cache.php's "only GET requests can hit the anonymous cache" gate
 * returns immediately and lets WordPress load for real -- purging through
 * wordpress.wp-cli, not wordpress.run-php, is what actually reaches the
 * plugin's own `wp extrachill-cache purge --all` command.
 */
function cachePurgeStep(journeyId, phase) {
  return {
    command: 'wordpress.wp-cli',
    args: ['command=extrachill-cache purge --all'],
    allowFailure: true,
    metadata: { kind: `journey-${phase}-cache-purge`, journey: journeyId },
  };
}

export async function buildJourneys(settings, topology) {
  const ids = journeySelection(settings);
  const known = await availableJourneys();
  for (const id of ids) {
    if (!known.includes(id)) {
      throw new Error(`Unknown extrachill_journeys entry '${id}'. Available journeys: ${known.join(', ') || '(none)'}.`);
    }
  }
  const loaded = [];
  for (const id of ids) {
    loaded.push(await loadJourney(id, topology));
  }
  return loaded;
}

export async function buildRecipe(settings = {}, cwd = process.cwd()) {
  const topology = await loadJson('network-topology.json');
  const components = await loadJson('components.json');

  const overrides = isRecord(settings.extrachill_component_source_overrides) ? settings.extrachill_component_source_overrides : {};
  const releaseSet = isRecord(settings.extrachill_release_set) ? settings.extrachill_release_set : {};
  const includeExcluded = new Set(Array.isArray(settings.extrachill_include_excluded_components) ? settings.extrachill_include_excluded_components : []);

  const activePlugins = [...components.plugins];
  for (const excluded of components.excludedComponents) {
    if (includeExcluded.has(excluded.slug) && overrides[excluded.slug]) {
      activePlugins.push({ slug: excluded.slug, source: 'override-only', activations: excluded.forcedActivations ?? [] });
    }
  }

  const extraPlugins = activePlugins.map((component) => ({
    source: resolveComponentSource(component, overrides, releaseSet),
    slug: component.slug,
    // wp-codebox validates a single pluginFile exists in the mounted source
    // regardless of activate:false; components whose main file does not
    // follow the <slug>/<slug>.php convention (e.g. the wp.org AI provider
    // plugins ship plugin.php) need it set explicitly. The rig itself
    // activates every declared activation below, not just this one.
    ...(component.activations?.[0]?.pluginFile ? { pluginFile: component.activations[0].pluginFile } : {}),
    activate: false,
    loadAs: 'plugin',
    metadata: { extrachillActivations: component.activations },
  }));

  const themeSource = settings.extrachill_theme_source;
  const theme = buildThemeInputs(components.theme, themeSource);

  const additionalPrepareSteps = recipeArray(settings.wordpress_runtime_prepare_steps, 'wordpress_runtime_prepare_steps');
  const additionalPostSteps = recipeArray(settings.wordpress_runtime_post_steps, 'wordpress_runtime_post_steps');
  const phpVersion = runtimePhpVersion(settings);

  const journeys = await buildJourneys(settings, topology);
  const demoMode = settings.extrachill_demo === true;
  const demoThemes = new Map();
  if (demoMode) {
    for (const { journey } of journeys) {
      if (!journey.demo) throw new Error(`Journey '${journey.id}' has no demo contract.`);
      if (!demoThemes.has(journey.demo.theme)) {
        demoThemes.set(journey.demo.theme, JSON.parse(await readFile(path.join(packageRoot, 'demo-themes', journey.demo.theme), 'utf8')));
      }
    }
  }

  const activationHookExceptions = (components.activationHookExceptions ?? []).map((entry) => entry.pluginFile);
  const activationMatrix = buildActivationMatrix(topology, activePlugins, components.excludedComponents, activationHookExceptions);

  const muPluginPath = await writeDomainIdsMuPlugin(artifactsRoot(cwd), topology);
  const sandboxCompatPath = await writeSandboxCompatMuPlugin(artifactsRoot(cwd));

  const runtimeEnv = {};
  for (const { journey } of journeys) {
    Object.assign(runtimeEnv, journey.runtimeEnv ?? {});
  }

  const cacheActive = activePlugins.some((component) => component.slug === 'extrachill-cache');

  // Journey fixture mu-plugins (extrachill-network/journey/v1's optional
  // "fixtureMuPlugins"): journey-owned PHP files that must run on EVERY
  // request for the lifetime of the boot, not just inside one run-php
  // step's own process (e.g. a persistent add_filter() a browser-driven
  // registration/delivery flow needs live while it makes its own separate
  // HTTP requests). Generic rig mounting; the vendor-specific content (a
  // Turnstile bypass filter, a provider HTTP stub, ...) lives entirely
  // inside the journey's own file, never in this rig.
  const journeyFixtureMuPluginMounts = [];
  for (const { journey, dir } of journeys) {
    for (const file of journey.fixtureMuPlugins ?? []) {
      journeyFixtureMuPluginMounts.push({
        type: 'file',
        source: path.join(dir, file),
        target: `/wordpress/wp-content/mu-plugins/journey-${journey.id}-${path.basename(file)}`,
        mode: 'readonly',
        metadata: { kind: 'journey-fixture-mu-plugin', journey: journey.id, file },
      });
    }
  }

  // extrachill_journey_seed: one optional, generic deterministic seed string
  // any journey's own seed.php may read (get_site_option('ec_rig_journey_seed', ...))
  // to build a replayable, seeded case plan (e.g. a fuzz campaign's generated
  // email/device IDs). The rig only carries the opaque string through; it
  // has no idea what a journey does with it.
  const journeySeed = journeySeedSetting(settings);

  const journeySteps = [];
  if (journeys.length > 0 && journeySeed !== undefined) {
    journeySteps.push(journeySeedStep(journeySeed));
  }
  for (const { journey, dir } of journeys) {
    const seed = journeyPhaseStep(journey, dir, 'seed');
    if (seed) {
      if (cacheActive) {
        journeySteps.push(cachePurgeStep(journey.id, 'seed'));
      }
      journeySteps.push(seed);
    }
    journeySteps.push(...journey.steps.map((step) => {
      const prepared = journeyStep(journey, dir, step);
      if (demoMode && step.command === 'wordpress.browser-actions') {
        prepared.args = [...prepared.args.filter((arg) => !arg.startsWith('capture=')), ...assembleDemoArgs(journey.demo, demoThemes.get(journey.demo.theme))];
        if (journey.demo.pacing) {
          prepared.args = prepared.args.map((arg) => arg.startsWith('steps-json=') ? `steps-json=${paceDemoSteps(arg.slice('steps-json='.length), journey.demo.pacing)}` : arg);
        }
      }
      return prepared;
    }));
    const grade = journeyPhaseStep(journey, dir, 'grade');
    if (grade) {
      if (cacheActive) {
        journeySteps.push(cachePurgeStep(journey.id, 'grade'));
      }
      journeySteps.push(grade);
    }
  }

  const workflowSteps = [
    activatePluginsStep(activationMatrix),
    ...(theme.activateStep ? [theme.activateStep] : []),
    activationAssertionStep(topology, activationMatrix, components.excludedComponents, includeExcluded),
    ...additionalPrepareSteps,
    ...topology.sites.map((site) => browserProbeStep(site)),
    ...journeySteps,
    ...additionalPostSteps,
  ];

  return {
    schema: 'wp-codebox/workspace-recipe/v1',
    runtime: {
      backend: 'wordpress',
      ...(settings.wordpress_runtime_version ? { wp: settings.wordpress_runtime_version } : {}),
      ...(phpVersion ? { phpVersion } : {}),
      blueprint: { steps: [] },
      preview: { siteUrl: `http://${topology.sites.find((site) => site.primary)?.domain ?? topology.sites[0].domain}/` },
    },
    inputs: {
      ...(Object.keys(runtimeEnv).length > 0 ? { runtimeEnv } : {}),
      extra_plugins: extraPlugins,
      ...(theme.extraThemes ? { extra_themes: theme.extraThemes } : {}),
      mounts: [
        {
          type: 'file',
          source: muPluginPath,
          target: `/wordpress/wp-content/mu-plugins/${DOMAIN_IDS_MU_PLUGIN_FILENAME}`,
          mode: 'readonly',
          metadata: { kind: 'extrachill-network-domain-ids', generated: true, note: 'Resolves EC_BLOG_ID_* constants from the actual sites table by domain; see run.mjs EC_DOMAIN_TO_BLOG_ID_CONSTANT.' },
        },
        {
          type: 'file',
          source: sandboxCompatPath,
          target: `/wordpress/wp-content/mu-plugins/${SANDBOX_COMPAT_MU_PLUGIN_FILENAME}`,
          mode: 'readonly',
          metadata: { kind: 'extrachill-network-sandbox-compat', generated: true, note: 'http/https URL resolution, Redis-less rate-limiter stores, SQLite advisory-lock answers; see run.mjs sandboxCompatMuPluginSource.' },
        },
        ...(theme.mounts ? theme.mounts : []),
        ...journeyFixtureMuPluginMounts,
      ],
      siteSeeds: [{
        type: 'parent_site',
        name: 'extrachill-network-topology',
        // parent_site export is not implemented upstream yet (recipe-site-seeds.ts
        // reports this seed as "skipped"), so no data actually crosses from
        // production; this scope only exists to satisfy schema validation's
        // bounded-scope requirement for a parent_site declaration.
        scopes: { options: { names: ['blogname'], maxRecords: 1 } },
        bootstrap: {
          multisite: {
            enabled: true,
            install: topology.install,
            sites: topology.sites.map((site) => ({ domain: site.domain, path: site.path, title: site.title })),
          },
          domains: topology.sites.map((site) => ({ domain: site.domain, path: site.path, primary: Boolean(site.primary) })),
        },
      }],
    },
    workflow: { steps: workflowSteps },
    artifacts: {
      directory: artifactsRoot(cwd),
    },
    ...(journeys.length > 0
      ? {
          metadata: {
            extrachillJourneys: journeys.map(({ journey }) => ({
              id: journey.id,
              persona: journey.persona?.id ?? null,
              sites: journey.sites,
            })),
          },
        }
      : {}),
  };
}

function artifactsRoot(cwd) {
  return process.env.HOMEBOY_ARTIFACT_ROOT || path.join(cwd, 'artifacts/extrachill-network');
}

function resolveComponentSource(component, overrides, releaseSet) {
  if (overrides[component.slug]) {
    return overrides[component.slug];
  }
  const pin = releaseSet[component.slug];
  if (component.source === 'wporg') {
    return `https://downloads.wordpress.org/plugin/${component.wporgSlug}.zip`;
  }
  if (component.source === 'github') {
    if (pin?.ref) {
      return `https://github.com/${component.repo}/releases/download/${pin.ref}/${component.asset}`;
    }
    return `https://github.com/${component.repo}/releases/latest/download/${component.asset}`;
  }
  if (component.source === 'override-only') {
    throw new Error(`Component ${component.slug} has no default source; supply extrachill_component_source_overrides.${component.slug}.`);
  }
  throw new Error(`Unknown component source strategy for ${component.slug}: ${component.source}`);
}

function buildThemeInputs(themeComponent, themeSource) {
  if (!themeSource) {
    return { extraThemes: undefined, mounts: undefined, activateStep: undefined };
  }
  const isRemote = /^https:\/\/.*\.zip$/i.test(themeSource.trim());
  if (isRemote) {
    // Forward-compatible with Automattic/wp-codebox#2519 (merged upstream,
    // not yet in the installed wp-codebox CLI as of this rig's authoring --
    // see components.json theme.note). Recipe validation will reject
    // inputs.extra_themes until the installed CLI updates past v0.26.12.
    return {
      extraThemes: [{ source: themeSource, slug: themeComponent.slug, activate: true }],
      mounts: undefined,
      activateStep: undefined,
    };
  }
  return {
    extraThemes: undefined,
    mounts: [{
      type: 'directory',
      source: themeSource,
      target: `/wordpress/wp-content/themes/${themeComponent.slug}`,
      mode: 'readonly',
      metadata: { kind: 'wordpress-theme', slug: themeComponent.slug },
    }],
    activateStep: activateThemeStep(themeComponent.slug),
  };
}

function activateThemeStep(slug) {
  const code = `$theme_slug = ${JSON.stringify(slug)};
if ( ! is_multisite() ) {
\tthrow new RuntimeException( 'Expected a multisite runtime.' );
}
foreach ( get_sites( array( 'number' => 0, 'fields' => 'ids' ) ) as $site_id ) {
\tswitch_to_blog( (int) $site_id );
\ttry {
\t\t$theme = wp_get_theme( $theme_slug );
\t\tif ( ! $theme->exists() ) {
\t\t\tthrow new RuntimeException( 'Mounted theme is unavailable: ' . $theme_slug );
\t\t}
\t\tswitch_theme( $theme_slug );
\t\tif ( get_stylesheet() !== $theme_slug ) {
\t\t\tthrow new RuntimeException( 'Unable to activate mounted theme: ' . $theme_slug );
\t\t}
\t} finally {
\t\trestore_current_blog();
\t}
}`;
  return { command: 'wordpress.run-php', args: [`code=${code}`], metadata: { kind: 'wordpress-theme-activation', slug } };
}

/** @returns {{ network: string[], perDomain: Record<string, string[]> }} */
function buildActivationMatrix(topology, activePlugins, excludedComponents, activationHookExceptions) {
  const network = [];
  const perDomain = Object.fromEntries(topology.sites.map((site) => [site.domain, []]));
  for (const component of activePlugins) {
    for (const activation of component.activations ?? []) {
      if (activation.scope === 'network') {
        network.push(activation.pluginFile);
        continue;
      }
      for (const domain of activation.scope) {
        if (!perDomain[domain]) {
          throw new Error(`components.json activation references unknown site domain: ${domain}`);
        }
        perDomain[domain].push(activation.pluginFile);
      }
    }
  }
  return { network, perDomain, excludedComponents, activationHookExceptions };
}

function activatePluginsStep(matrix) {
  const encoded = Buffer.from(JSON.stringify({ network: matrix.network, perDomain: matrix.perDomain }), 'utf8').toString('base64');
  const code = `require_once ABSPATH . 'wp-admin/includes/plugin.php';
require_once ABSPATH . 'wp-admin/includes/upgrade.php';
$matrix = json_decode(base64_decode('${encoded}'), true);
if (!is_array($matrix)) {
    throw new RuntimeException('extrachill-network activation matrix did not decode.');
}

/**
 * A plugin's own activation hook can legitimately call wp_die() to hard-fail
 * an unmet requirement (extrachill-events-network-blocks does exactly this
 * when it is not being network-activated). This step batches every
 * network-wide AND per-site activation into ONE PHP process; an uncaught
 * wp_die() from any single plugin's hook -- fired with hooks enabled since
 * this step deliberately activates with $silent=false -- kills that whole
 * process, leaving every plugin queued after it in $matrix['network'] with
 * NO activation attempt at all and no evidence recorded. That is exactly
 * what produced "16 of 17 network plugins inactive, empty evidence" during
 * this rig's own bring-up: the JSON-declaration-order boundary matched
 * precisely where the first hard-failing hook's wp_die() aborted the batch.
 * Convert wp_die() into a catchable exception for the lifetime of this step
 * so one plugin's hard-fail becomes a normal, retried per-plugin activation
 * error in the evidence -- never a silent abort of every plugin after it.
 */
class Extrachill_Network_Rig_Activation_Die extends RuntimeException {}
add_filter('wp_die_handler', function () {
    return function ($message, $title = '', $args = array()) {
        unset($args);
        $text = is_wp_error($message) ? $message->get_error_message() : (is_string($message) ? $message : wp_json_encode($message));
        throw new Extrachill_Network_Rig_Activation_Die(trim($text . ($title !== '' ? " ({$title})" : '')));
    };
}, PHP_INT_MAX);

/**
 * components.json lists plugins independent of each other's "Requires
 * Plugins" headers or runtime dependency checks (WooCommerce before
 * extrachill-shop, etc.). Rather than hand-order every entry (fragile as
 * soon as a component adds a new dependency), retry the whole pending list
 * across multiple passes: WordPress activates whatever's dependencies are
 * already satisfied each pass, and progress strictly increases until either
 * everything activates or a real, non-ordering failure remains.
 */
function extrachill_network_activate_with_retries($plugin_files, $network_wide, &$evidence_errors) {
    $pending = array_values(array_unique($plugin_files));
    $last_errors = array();
    while (count($pending) > 0) {
        $still_pending = array();
        $activated_this_pass = 0;
        foreach ($pending as $plugin_file) {
            if (!file_exists(WP_PLUGIN_DIR . '/' . $plugin_file)) {
                throw new RuntimeException('extrachill-network: plugin file missing after mount: ' . $plugin_file);
            }
            $already_active = $network_wide ? is_plugin_active_for_network($plugin_file) : is_plugin_active($plugin_file);
            if ($already_active) {
                $activated_this_pass++;
                continue;
            }
            try {
                $result = activate_plugin($plugin_file, '', $network_wide, false);
            } catch (Extrachill_Network_Rig_Activation_Die $e) {
                $last_errors[$plugin_file] = 'wp_die: ' . $e->getMessage();
                $evidence_errors[$plugin_file] = 'wp_die: ' . $e->getMessage();
                $still_pending[] = $plugin_file;
                continue;
            }
            if (is_wp_error($result)) {
                /**
                 * Core's own activate_plugin() (wp-admin/includes/plugin.php)
                 * commits the active-plugin option write BEFORE its trailing
                 * ob_get_length() > 0 check -- an 'unexpected_output' WP_Error
                 * means some stray warning/notice leaked into the output
                 * buffer during the plugin's own load or activation hook, NOT
                 * that activation failed. Re-check the real activation state
                 * rather than trusting the WP_Error at face value: this rig
                 * hit that exact combination activating WooCommerce (a PHP
                 * 8.4 deprecation notice leaks into the buffer that WP core
                 * itself already tolerates as an activated-but-noisy plugin).
                 * Retrying it forever as though it never activated is wrong
                 * and, worse, permanently blocks anything depending on it
                 * from ever making progress.
                 */
                $now_active = $network_wide ? is_plugin_active_for_network($plugin_file) : is_plugin_active($plugin_file);
                if ($now_active && $result->get_error_code() === 'unexpected_output') {
                    $evidence_errors[$plugin_file] = 'ok (activated with unexpected_output tolerated: ' . $result->get_error_message() . ')';
                    $activated_this_pass++;
                    continue;
                }
                $last_errors[$plugin_file] = $result->get_error_message();
                $evidence_errors[$plugin_file] = $result->get_error_code() . ': ' . $result->get_error_message();
                $still_pending[] = $plugin_file;
                continue;
            }
            $evidence_errors[$plugin_file] = 'ok (hook fired: ' . (did_action('activate_' . $plugin_file) > 0 ? 'yes' : 'NO') . ')';
            $activated_this_pass++;
        }
        if ($activated_this_pass === 0) {
            $details = array();
            foreach ($still_pending as $plugin_file) {
                $details[] = $plugin_file . ': ' . ($last_errors[$plugin_file] ?? 'unknown error');
            }
            throw new RuntimeException('extrachill-network: could not activate (dependency ordering or a real failure): ' . implode('; ', $details));
        }
        $pending = $still_pending;
    }
}

/**
 * Known per-site tables whose owning plugin's activation hook can report a
 * clean, hook-fired success (activate_plugin() returns null, no WP_Error, no
 * buffered output, did_action() > 0) while the table itself is still missing
 * immediately afterward, in the SAME request and blog context. Instrumented
 * live during this rig's own bring-up for data-machine-events specifically:
 * its activation hook's own EventDatesTable::create_table() call left the
 * table missing right after activation, and re-firing the WHOLE activation
 * hook a second time did not reliably fix it either (still reproduced on a
 * later run) -- only calling create_table() again, directly, did. The root
 * cause is unconfirmed (a Playground/SQLite dbDelta timing quirk under this
 * rig's own heavy switch_to_blog() + repeated-activation churn is the
 * leading theory; production activates each plugin in its own request and
 * never exercises this path) and is filed upstream with the evidence
 * gathered here. This list is the explicit, named, evidence-logged safety
 * net -- not a silent workaround: it only repairs a table for a plugin this
 * step already verified is genuinely active, and it always records what it
 * found in $activation_errors so the run's evidence shows exactly what
 * happened. See components.json's activationHookExceptions for the parallel
 * "expected, named, reasoned" pattern this follows for whole-plugin gaps.
 *
 * @param string $plugin_file    Basename the table's owning plugin activates as.
 * @param string $table_exists_callable PHP callable string, e.g. "Class::method".
 * @param string $create_callable      PHP callable string, e.g. "Class::method".
 */
function extrachill_network_repair_known_table($plugin_file, $table_exists_callable, $create_callable, $site_domain, &$evidence_errors) {
    if (!is_callable($table_exists_callable) || !is_callable($create_callable)) {
        return;
    }
    if (call_user_func($table_exists_callable)) {
        return;
    }
    call_user_func($create_callable);
    $now_exists = call_user_func($table_exists_callable);
    $evidence_errors[$plugin_file . '@' . $site_domain . '@table-repair'] = $now_exists
        ? 'repaired: table missing immediately after a clean activation-hook fire; direct ' . $create_callable . '() call created it'
        : 'UNRESOLVED: table still missing after a direct ' . $create_callable . '() repair attempt';
}

function extrachill_network_repair_known_tables($active_plugin_files, $site_domain, &$evidence_errors) {
    $known = array(
        array(
            'pluginFile' => 'data-machine-events/data-machine-events.php',
            'tableExists' => 'DataMachineEvents\\Core\\EventDatesTable::table_exists',
            'create' => 'DataMachineEvents\\Core\\EventDatesTable::create_table',
        ),
    );
    foreach ($known as $entry) {
        if (!in_array($entry['pluginFile'], $active_plugin_files, true)) {
            continue;
        }
        extrachill_network_repair_known_table($entry['pluginFile'], $entry['tableExists'], $entry['create'], $site_domain, $evidence_errors);
    }
}

$activation_errors = array();
extrachill_network_activate_with_retries($matrix['network'], true, $activation_errors);
$expected_network = array_values(array_unique($matrix['network']));
$still_missing_network = array_values(array_diff($expected_network, array_keys(get_site_option('active_sitewide_plugins', array()))));

// Plugins whose own activation hook deactivated them again: their activation
// ran (hooks fired) and the plugin opted out because a backing service the
// sandbox lacks is required (a Redis server, a vendor API, ...). That is an
// environment degradation, not an activation failure -- record it for the
// assertion step instead of failing the boot, and re-mark the plugin active
// WITHOUT re-running hooks so the mounted plugin matrix still matches
// production for code-path parity. A plugin that never activated at all
// (hook never fired) stays a hard failure.
$self_deactivated_network = array_values(array_filter($still_missing_network, function ($plugin_file) {
    return did_action('activate_' . $plugin_file) > 0;
}));
foreach ($self_deactivated_network as $missing_plugin_file) {
    activate_plugin($missing_plugin_file, '', true, true);
}
update_site_option('ec_rig_self_deactivated_network', $self_deactivated_network, false);

foreach (get_sites(array('number' => 0)) as $site) {
    switch_to_blog((int) $site->blog_id);
    try {
        // Network activation fires each plugin's activation hook exactly once,
        // network-wide, from this request's current site. Plugins whose setup is
        // per-site (tables on the site's own prefix, per-site options, CPT
        // state) were installed in production by single-site activation firing
        // their hooks with $network_wide=false on every site. Re-fire the
        // activation hook per site here for the same coverage; the callbacks
        // are idempotent (dbDelta, options guards, taxonomy_exists checks).
        foreach ($matrix['network'] as $network_plugin_file) {
            if (!file_exists(WP_PLUGIN_DIR . '/' . $network_plugin_file)) {
                continue;
            }
            try {
                do_action('activate_' . $network_plugin_file, false);
            } catch (Extrachill_Network_Rig_Activation_Die $e) {
                // Same wp_die-to-exception protection as the network-wide
                // pass: a per-site re-fire hard-failing must not abort setup
                // for every other plugin on this site (or every later site).
                $activation_errors[$network_plugin_file . '@' . $site->domain] = 'wp_die on per-site re-fire: ' . $e->getMessage();
            }
        }
        $plugin_files = $matrix['perDomain'][$site->domain] ?? array();
        try {
            extrachill_network_activate_with_retries($plugin_files, false, $activation_errors);
        } catch (RuntimeException $e) {
            throw new RuntimeException($site->domain . ': ' . $e->getMessage());
        }
        extrachill_network_repair_known_tables($plugin_files, $site->domain, $activation_errors);
    } finally {
        restore_current_blog();
    }
}
$final_per_domain = array();
foreach (get_sites(array('number' => 0)) as $site) {
    switch_to_blog((int) $site->blog_id);
    $final_per_domain[$site->domain] = get_option('active_plugins', array());
    restore_current_blog();
}
update_site_option('ec_rig_activation_report', array('errors' => $activation_errors, 'selfDeactivatedNetwork' => $self_deactivated_network, 'finalNetworkActive' => array_keys(get_site_option('active_sitewide_plugins', array())), 'finalPerDomain' => $final_per_domain), false);
echo wp_json_encode(array('activated' => true, 'selfDeactivatedNetwork' => $self_deactivated_network, 'activationErrors' => $activation_errors));`;
  return { command: 'wordpress.run-php', args: [`code=${code}`], metadata: { kind: 'extrachill-network-activation' } };
}

function activationAssertionStep(topology, matrix, excludedComponents, includeExcluded) {
  const excludedSlugs = excludedComponents.filter((excluded) => !includeExcluded.has(excluded.slug)).map((excluded) => ({ slug: excluded.slug, scope: excluded.scope, reason: excluded.reason }));
  const expected = {
    network: matrix.network,
    perDomain: matrix.perDomain,
    excludedComponents: excludedSlugs,
    activationHookExceptions: matrix.activationHookExceptions ?? [],
    expectedHomepageStatus: Object.fromEntries(topology.sites.map((site) => [site.domain, site.expectedHomepageStatus ?? [200]])),
  };
  const encoded = Buffer.from(JSON.stringify(expected), 'utf8').toString('base64');
  const code = `require_once ABSPATH . 'wp-admin/includes/plugin.php';
$expected = json_decode(base64_decode('${encoded}'), true);
$report = array('sites' => array(), 'network' => array(), 'excludedComponents' => $expected['excludedComponents']);
$activation_report = get_site_option('ec_rig_activation_report', array());
if (is_array($activation_report)) {
    $report['activationDiagnostics'] = $activation_report;
}
$active_network = array_keys(get_site_option('active_sitewide_plugins', array()));
sort($active_network);
$expected_network = $expected['network'];
sort($expected_network);
$tolerated_network = array_values(array_intersect($expected['activationHookExceptions'], array_diff($expected_network, $active_network)));
$report['network'] = array(
    'expected' => $expected_network,
    'actual' => $active_network,
    'missing' => array_values(array_diff($expected_network, $active_network)),
    'unexpected' => array_values(array_diff($active_network, $expected_network)),
    'toleratedEnvironmentDeactivated' => $tolerated_network,
);
$hard_missing_network = array_values(array_diff($report['network']['missing'], $tolerated_network));
if (!empty($hard_missing_network)) {
    $diag = '';
    if (is_array($activation_report) && !empty($activation_report['errors'])) {
        $lines = array();
        foreach ($activation_report['errors'] as $plugin_file => $outcome) {
            $lines[] = $plugin_file . ' => ' . $outcome;
        }
        $diag = ' | activation evidence: ' . implode('; ', $lines);
    }
    throw new RuntimeException('extrachill-network: network plugins not active after setup: ' . implode(', ', $hard_missing_network) . $diag);
}
foreach (get_sites(array('number' => 0)) as $site) {
    switch_to_blog((int) $site->blog_id);
    try {
        $active = get_option('active_plugins', array());
        sort($active);
        $expected_site = $expected['perDomain'][$site->domain] ?? array();
        sort($expected_site);
        $missing = array_values(array_diff($expected_site, $active));
        $unexpected = array_values(array_diff($active, $expected_site));
        // No server-side home-page request here: network domains are the
        // real production hostnames, and Playground resolves PHP HTTP on the
        // real internet, so a wp_remote_get(home_url()) measured PRODUCTION,
        // not this boot. Each site's page load is judged in-sandbox by its
        // baseline browser probe (routed through the sandbox proxy).
        $report['sites'][$site->domain] = array(
            'theme' => get_stylesheet(),
            'expectedActivePlugins' => $expected_site,
            'actualActivePlugins' => $active,
            'missingPlugins' => $missing,
            'unexpectedActivePlugins' => $unexpected,
        );
        if (!empty($missing)) {
            throw new RuntimeException('extrachill-network: ' . $site->domain . ' missing expected plugins: ' . implode(', ', $missing));
        }
    } finally {
        restore_current_blog();
    }
}
echo wp_json_encode(array('schema' => 'extrachill-network/activation-report/v1', 'report' => $report));`;
  return { command: 'wordpress.run-php', args: [`code=${code}`], metadata: { kind: 'extrachill-network-assertion' } };
}

function browserProbeStep(site) {
  // A site whose expectedHomepageStatus tolerates non-200 (see
  // network-topology.json for why extrachill.link is one) will legitimately
  // log a "failed to load resource" console entry for the document response
  // itself; only assert no-console-errors where 200 is the sole expectation.
  const expectedStatus = site.expectedHomepageStatus ?? [200];
  const strictStatus = expectedStatus.length === 1 && expectedStatus[0] === 200;
  return {
    command: 'wordpress.browser-probe',
    args: [
      `url=http://${site.domain}/`,
      `route-host=${site.domain}`,
      'network-policy=block',
      `allow-host=${site.domain}`,
      ...(strictStatus ? ['assert=no-console-errors'] : []),
      'assert=no-page-errors',
      // WordPress renders its critical-error screen in .wp-die-message.
      'assert=not-exists:.wp-die-message',
      'capture=console,errors,html,network,screenshot',
    ],
    metadata: { kind: 'extrachill-network-baseline-page-load', domain: site.domain },
  };
}

// Production runs PHP 8.4.x (verified read-only via `wp eval 'echo PHP_VERSION;'`
// on extrachill.com, 2026-09-23) and several network plugins (e.g.
// extrachill-api) declare "Requires PHP: 8.4" and refuse to activate on
// WP Codebox's own 8.3 default runtime. Default to 8.4; callers can still pin
// a different supported version.
const DEFAULT_PHP_VERSION = '8.4';

function runtimePhpVersion(settings) {
  if (!Object.hasOwn(settings, 'wordpress_runtime_php_version')) {
    return DEFAULT_PHP_VERSION;
  }
  const value = settings.wordpress_runtime_php_version;
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error('wordpress_runtime_php_version must be a non-empty PHP major.minor version.');
  }
  return value.trim();
}

function recipeArray(value, label) {
  if (value === undefined) {
    return [];
  }
  if (!Array.isArray(value)) {
    throw new Error(`${label} must be an array.`);
  }
  return value;
}

function isRecord(value) {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

async function main() {
  const dryRun = process.argv.includes('--dry-run');
  const settings = parseSettings(process.env.HOMEBOY_SETTINGS_JSON);
  const recipe = await buildRecipe(settings);
  if (settings.extrachill_demo === true) assertDemoCodeboxVersion();
  const temporary = await mkdtemp(path.join(os.tmpdir(), 'extrachill-network-'));
  const recipePath = path.join(temporary, 'recipe.json');
  const resultPath = process.env.HOMEBOY_NETWORK_RESULT_FILE || path.join(temporary, 'result.json');
  await writeFile(recipePath, `${JSON.stringify(recipe, null, 2)}\n`);

  try {
    runCodebox(['recipe', 'validate', '--recipe', recipePath, '--json'], true);
    const args = ['recipe-run', '--recipe', recipePath, '--artifacts', recipe.artifacts.directory, '--json'];
    if (dryRun) {
      args.push('--dry-run');
    }
    const result = runCodebox(args, true);
    await mkdir(path.dirname(resultPath), { recursive: true });
    await writeFile(resultPath, result.stdout);
    const envelope = JSON.parse(result.stdout);
    if (!dryRun && envelope.success !== true) {
      throw new Error('WP Codebox extrachill-network recipe did not succeed.');
    }
    if (!dryRun && settings.extrachill_demo === true) {
      const topology = await loadJson('network-topology.json');
      const demoJourneys = (await buildJourneys(settings, topology)).map(({ journey }) => journey);
      await renderJourneyDemos(recipe, demoJourneys);
    }
    process.stdout.write(result.stdout);
  } finally {
    await rm(temporary, { recursive: true, force: true });
  }
}

function assertDemoCodeboxVersion() {
  const executable = process.env.HOMEBOY_WP_CODEBOX_BIN || process.env.WP_CODEBOX_BIN || 'wp-codebox';
  const result = spawnSync(executable, ['--version'], { encoding: 'utf8' });
  const version = `${result.stdout ?? ''} ${result.stderr ?? ''}`.match(/\b(\d+)\.(\d+)\.(\d+)\b/)?.[0];
  if (!version || compareVersions(version, DEMO_MIN_WP_CODEBOX_VERSION) < 0) {
    throw new Error(`Demo mode requires WP Codebox >= ${DEMO_MIN_WP_CODEBOX_VERSION}; found ${version ?? 'unknown'}.`);
  }
}

function compareVersions(a, b) {
  const left = a.split('.').map(Number); const right = b.split('.').map(Number);
  for (let i = 0; i < 3; i++) if (left[i] !== right[i]) return left[i] - right[i];
  return 0;
}

async function renderJourneyDemos(recipe, journeys) {
  const ffmpeg = spawnSync('ffmpeg', ['-version'], { encoding: 'utf8' });
  if (ffmpeg.error || ffmpeg.status !== 0) throw new Error('Demo rendering requires ffmpeg on PATH. Install ffmpeg (https://ffmpeg.org/download.html) and retry.');
  const files = await listFiles(recipe.artifacts.directory);
  const summaries = [];
  for (const file of files.filter((candidate) => candidate.endsWith(path.join('files', 'browser', 'action-summary.json')))) {
    try {
      const summary = JSON.parse(await readFile(file, 'utf8'));
      if (summary.video?.path) summaries.push({ dir: path.dirname(path.dirname(path.dirname(file))), summary });
    } catch { /* not a browser-actions summary */ }
  }
  for (const journey of journeys) {
    const markers = new Set(journeyMarkers(journey));
    const match = summaries.find(({ summary }) => (summary.video.markers ?? []).some((marker) => markers.has(marker.name)));
    if (!match) throw new Error(`Demo video for journey '${journey.id}' was not found in the run artifacts.`);
    const output = path.join(packageRoot, 'evidence', 'demo', `${journey.id}.mp4`);
    await mkdir(path.dirname(output), { recursive: true });
    const input = path.join(match.dir, match.summary.video.path);
    const encoded = spawnSync('ffmpeg', demoEncodeArgs(input, output, journey.demo), { stdio: 'inherit' });
    if (encoded.status !== 0) throw new Error(`ffmpeg failed encoding demo for ${journey.id}.`);
    if (journey.demo.cover) {
      const coverMarker = (match.summary.video.markers ?? []).find((marker) => marker.name === journey.demo.cover.marker);
      if (!coverMarker) throw new Error(`Cover marker '${journey.demo.cover.marker}' for journey '${journey.id}' is missing from the recorded video.`);
      const cover = path.join(path.dirname(output), `${journey.id}-cover.png`);
      const coverArgs = ['-y', '-v', 'error', '-ss', String((coverMarker.endMs + 700) / 1000), '-i', input, '-frames:v', '1'];
      const size = journey.demo.video.output;
      if (size) coverArgs.splice(coverArgs.length - 2, 0, '-vf', `scale=${size.width}:${size.height}:flags=lanczos`);
      coverArgs.push(cover);
      const extracted = spawnSync('ffmpeg', coverArgs, { stdio: 'inherit' });
      if (extracted.status !== 0) throw new Error(`ffmpeg failed extracting cover for ${journey.id}.`);
    }
    for (const marker of match.summary.video.markers ?? []) {
      if (!marker.name) continue;
      const still = path.join(path.dirname(output), `${journey.id}-${marker.name}.png`);
      spawnSync('ffmpeg', ['-y', '-v', 'error', '-ss', String((marker.endMs + 700) / 1000), '-i', input, '-frames:v', '1', still], { stdio: 'inherit' });
    }
  }
}

async function listFiles(directory) {
  try {
    const entries = await readdir(directory, { withFileTypes: true });
    return (await Promise.all(entries.map((entry) => entry.isDirectory() ? listFiles(path.join(directory, entry.name)) : [path.join(directory, entry.name)]))).flat();
  } catch { return []; }
}

export function runCodebox(args, capture = false) {
  const executable = process.env.HOMEBOY_WP_CODEBOX_BIN || process.env.WP_CODEBOX_BIN || 'wp-codebox';
  const maxBuffer = codeboxMaxBuffer();
  const env = { ...DEFAULT_DOWNLOAD_ENV, ...process.env };
  const result = spawnSync(executable, args, { encoding: 'utf8', stdio: capture ? 'pipe' : 'inherit', maxBuffer, env });
  if (result.error) {
    result.error.stdout = result.stdout || '';
    result.error.stderr = result.stderr || '';
    result.error.maxBuffer = maxBuffer;
    throw result.error;
  }
  if (capture && result.stderr) {
    process.stderr.write(result.stderr);
  }
  if (result.status !== 0) {
    // Surface Codebox's own diagnostics: CI discards this script's stdout, so a
    // failing `recipe validate` would otherwise report only an exit status.
    if (capture && result.stdout) {
      process.stderr.write(result.stdout);
    }
    const error = new Error(`WP Codebox exited with status ${result.status}.`);
    error.stdout = result.stdout || '';
    error.stderr = result.stderr || '';
    error.status = result.status;
    throw error;
  }
  return result;
}

function codeboxMaxBuffer() {
  const raw = process.env.HOMEBOY_WP_CODEBOX_MAX_BUFFER_BYTES;
  if (raw === undefined || raw === '') {
    return WP_CODEBOX_MAX_BUFFER_BYTES;
  }
  const value = Number(raw);
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new Error('HOMEBOY_WP_CODEBOX_MAX_BUFFER_BYTES must be a positive integer.');
  }
  return value;
}

function parseSettings(raw) {
  if (!raw) {
    return {};
  }
  const value = JSON.parse(raw);
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('HOMEBOY_SETTINGS_JSON must contain a JSON object.');
  }
  return value;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
